version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/php/Dockerfile
    container_name: smb-bo-app-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    networks:
      - smb-bo-network
    depends_on:
      - mysql
      - mongo
      - redis

  nginx:
    image: nginx:stable
    container_name: smb-bo-nginx-dev
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ../../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smb-bo-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: smb-bo-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smb_bo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smb-bo-network

  mongo:
    image: mongo:6.0
    container_name: smb-bo-mongo-dev
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - smb-bo-network

  redis:
    image: redis:7-alpine
    container_name: smb-bo-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - smb-bo-network

networks:
  smb-bo-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
